on:
  workflow_dispatch:

name: Deploy

jobs:
   build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.LOG_IN_CREDENTIALS }}
    - uses: azure/arm-deploy@v1
      with:
        resourceGroupName: ${{ vars.TEAM_21_RESOURCE_GROUPNAME }}
        template: ./InfrastructureAsCode/main.bicep
