name: Manual Trigger Workflow

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    
    steps:
      - name: step1
        run: echo "This is Step 1"

      - name: step2
        run: echo "This is Step 2"

  job2:
    runs-on: ubuntu-latest

    steps:
      - name: Call a GitHub Action (Cowsays)
        uses: mscoutermarsh/cowsays-action@master
        with:
          text: 'Team 21 is the best!'
          color: 'magenta'
